### ISSUE TITLE
Question: Where did you run the reference file generation?

### ISSUE THREAD

**Issue by rutkovskii** [carbonplan/kerchunk-NEX-GDDP-CMIP6#15]
Hello,

First, I wanted to express my genuine fascination with the work you have done and the attention to the details that you brought!

I have a question regarding the computational aspect mentioned in your `generation/parallel_reference_generation.ipynb notebook`. It states, 
> "Processing this 36 TB dataset with coiled cost approximately $5 of AWS Compute." 

Could you please mention where you ran your reference file generation and/or where you ran all your computations?

**Comment by norlandrhagen** [comment]
Hey there @rutkovskii, glad to hear you enjoyed the repo!

We ran the Kerchunk reference generation script via (coiled)[https://www.coiled.io/], which is a Dask based SaaS. We tuned a few knobs to reduce compute cost.
- Choosing small workers t4g.small
- Choosing to use spot instances
- Specifying worker with ARM processing architecture, which is cheaper on AWS.

You could also run this without coiled with a standard dask distributed cluster on whatever machine you want.

**Comment by rutkovskii** [comment]
I understand now. Thank you @norlandrhagen for your prompt reply!

To confirm my understanding, Coiled uses AWS underneath to spawn clusters of spot instances with specified characteristics, and Dask is used to do the computations on the Coiled cluster, did I get it right?

And for your use case, the cost (~$5) was only the cost of using AWS since it did not go over the free tier provided by Coiled, correct?

**Comment by norlandrhagen** [comment]
No problem!

1. Yup, but I'm not a coiled expert. I think you could also use machines from Azure, GCP etc. 
2. We were within the free tier for coiled, so the cost was our underlying AWS cloud bill. Coiled makes it super easy to see how much a job costs, which is pretty cool.

**Comment by rutkovskii** [comment]
Thank you so much!
