### ISSUE TITLE
Spatial subsetting very slow

### ISSUE THREAD

**Issue by bradleyswilson** [carbonplan/kerchunk-NEX-GDDP-CMIP6#16]
First off, thanks for making this all public, it's been very helpful to dig into the different methods and options!

I'm working on a use case where I essentially need only a single point or a few grid points from each GCM. I've implemented a simple clip function using `ds.sel`, but am finding that the subsequent zarr exports take almost as long as exporting the full dataset, which is quite surprising to me given how small the files are. For example (see code below), following the Kerchunk example and exporting 1 year of data for a single grid point only saves ~9 seconds relative to not clipping at all! 

I've attempted a number of chunking alternatives, but nothing seems to improve the export speed. Any ideas? Or is this just a fundamental limitation of this type of approach?

```{python}
def clip_netcdf(ds, bounds): 
    # Clips a netCDF file to bounds
    ds = ds.assign_coords(lon=(((ds.lon + 180) % 360) - 180)).sortby('lon')
    centroid = bounds.union_all().centroid
    return ds.sel(lat=centroid.y, lon=centroid.x, method='nearest')
    
def export_zarr(ds):
    ds = ds.isel(time=slice(0, 365))
    output = (
        "test.zarr"
    )     
    return ds.to_zarr(output, consolidated=True, compute=True, mode="w")

def export_zarr_clip(ds):
    ds = clip_dataset(ds, bounds)
    ds = ds.isel(time=slice(0, 365))
    output = (
        "test2.zarr"
    )     
    return ds.to_zarr(output, consolidated=True, compute=True, mode="w")
    
export_zarr(ds_list[1]) # ~57 seconds
export_zarr_clip(ds_list[1]) # 48 seconds

```

**Comment by norlandrhagen** [comment]
Hey there  @bradleyswilson, 

Glad you found a use for the repo! Maybe we can figure out a bit more about what's going on. 

The main limitation with this method (Kerchunk, Virtualizarr) is that the underlying chunking structure can't be changed without writing a new dataset. It seems like we have no spatial chunking in the dataset, so doing a spatial selection will have to load the full spatial extent.  If you only want a small spatial selection, you could do a `.sel` and write that selection to an new Zarr store you use for analysis. 

<img width="530" alt="image" src="https://github.com/user-attachments/assets/095025b5-2eb6-497a-82e6-9459328153fb">

That being said, I would think once you have a selection saving a smaller Zarr store should be quicker 😕 . Maybe the `.sel` and coord assignment is offsetting the time savings of writing a smaller Zarr store. A few suggestions that might help tease apart the timings. 
- Time each operation with a .load() after it or try a profiler. Xarray does a great job at being lazy and can usually defer any computation / loading until `.to_zarr()` or `.load` is called.
- If you're not using dask, starting up a client and looking at the dashboard should help diagnose a bit and speed up processing.
- I think the underlying NetCDF files as well as the reference are stored in `us-west-2`. If you have the ability, using compute in the same region should help.

Looking forward to see what you find!

```python

# pip install kerchunk fastparquet s3fs xarray coiled ipykernel bokeh jupyter dask
import xarray as xr 
ds = xr.open_dataset('s3://carbonplan-share/nasa-nex-reference/references_prod/ACCESS-CM2_historical/reference.parquet', engine='kerchunk', chunks={})

def export_zarr(ds):
    ds = ds.isel(time=slice(0,1000))[['hurs']]
    ds.to_zarr('full.zarr', consolidated=True, compute=True, mode="w")


def export_zarr_clip(ds):
    sds = ds.isel(time=slice(0,1000))[['hurs']]
    sds = sds.assign_coords(lon=(((ds.lon + 180) % 360) - 180)).sortby('lon')
    # Note: You could try removing this and transforming your input longitude coord to 0-360 instead of sorting the coords.
    # sds = sds.assign_coords(lon=(((ds.lon + 180) % 360) - 180)).sortby('lon')
    sds_sel = sds.sel(lat=47,lon=-122, method='nearest')
    sds_sel.to_zarr('clip.zarr', consolidated=True, compute=True, mode="w")
    
```

```
%%time
export_zarr(ds)

# CPU times: user 1min 15s, sys: 5.23 s, total: 1min 20s
# Wall time: 51.8 s

```

```
%%time
export_zarr_clip(ds)

# CPU times: user 23.5 s, sys: 4.52 s, total: 28.1 s
# Wall time: 54.9 s

```

**Comment by bradleyswilson** [comment]
thanks for the rapid response @norlandrhagen, this confirms a lot of what I suspected might be the case. 

Running a .sel and writing that selection to a new Zarr store for analysis was exactly my plan. After a bit more testing, I'm pretty confident that it's just the data loading the full spatial extent that's taking so much time. When I split-timed calling `.load()` versus the `to_zarr()`, it's the load that takes almost all the time. The writing is trivial once the data is in memory. 

This approach might not be prohibitive if I can spin up enough workers, I'll have to see if I have the capacity to do that. It's pretty fast to just wrap a bunch of spatial subset downloads from the THREDDS server for my use case though, so that might be preferable. 

Either way, learned a lot from digging in here and definitely will keep in mind for larger study areas.

**Comment by norlandrhagen** [comment]
> Running a .sel and writing that selection to a new Zarr store for analysis was exactly my plan. After a bit more testing, I'm pretty confident that it's just the data loading the full spatial extent that's taking so much time. When I split-timed calling `.load()` versus the `to_zarr()`, it's the load that takes almost all the time. The writing is trivial once the data is in memory.

Oh nice! Just to clarify, it's usually best practice to not call `.load()` or `.compute()` and just defer until the `to_zarr()`.

 
> 
> This approach might not be prohibitive if I can spin up enough workers, I'll have to see if I have the capacity to do that. It's pretty fast to just wrap a bunch of spatial subset downloads from the THREDDS server for my use case though, so that might be preferable.
> 
Totally! I don't know if you're familiar with using [xarray and dask](https://projectpythia.org/dask-cookbook/notebooks/03-dask-xarray.html). But it's a pretty easy way to use all your available workers with Xarray. The parallel spatial subset downloads from THREDDS sounds like an neat approach as well.

```
from distributed import Client
n_workers = 8 # Adjust as needed
client = Client(n_workers=n_workers)
client

ds = xr.open_dataset(...,chunks={})

...
ds.to_zarr(...)
```
> Either way, learned a lot from digging in here and definitely will keep in mind for larger study areas.

Thanks for checking out the repo!
